name: Unit-tests (Jest) + Coverage

defaults:
  run:
    shell: bash
    working-directory: src

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install pnpm@7 firebase-tools -g

      - uses: actions/setup-node@v3
        with:
          node-version: "18.0.0"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use ${{ secrets.FIREBASE_PROJECT }}
          chmod +x $GITHUB_WORKSPACE/.github/scripts/install_dependencies.sh
          bash $GITHUB_WORKSPACE/.github/scripts/install_dependencies.sh

      - name: Run tests
        run: pnpm install && pnpm test:coverage
